name: SIDD
model_type: ImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 78

datasets:
  train:
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: /work/sychien421/Datasets/SIDD/train/gt_crops.lmdb
    dataroot_lq: /work/sychien421/Datasets/SIDD/train/input_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD_val
    type: PairedImageDataset
    dataroot_gt: /work/sychien421/Datasets/SIDD/val/gt_crops.lmdb
    dataroot_lq: /work/sychien421/Datasets/SIDD/val/input_crops.lmdb
    io_backend:
      type: lmdb

network_g:
  type: Concertormer
  width: 48
  ffn_expansion_factor: 2
  enc_blk_nums: [2, 4, 8]
  middle_blk_num: 16
  dec_blk_nums: [8, 4, 4]
  enc_heads: [1, 2, 4]
  middle_heads: 8
  dec_heads: [4, 2, 1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: MSL1FFTLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
