name: GoPro
model_type: ImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 100

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: /work/sychien421/Datasets/Motion_Deblurring/GoPro/train/sharp_crops.lmdb
    dataroot_lq: /work/sychien421/Datasets/Motion_Deblurring/GoPro/train/blur_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 320
    use_flip: true
    use_rot: true

    progressive_training: True
    mini_batch_sizes: [8, 2, 1]
    iters: [200000, 300000, 100000]
    gt_sizes: [128, 256, 320]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: /work/sychien421/Datasets/Motion_Deblurring/GoPro/val/target_crops.lmdb
    dataroot_lq: /work/sychien421/Datasets/Motion_Deblurring/GoPro/val/input_crops.lmdb
    io_backend:
      type: lmdb

network_g:
  type: Concertormer
  width: 48
  ffn_expansion_factor: 2
  enc_blk_nums: [6, 8, 24]
  middle_blk_num: 2
  dec_blk_nums: [24, 8, 8]
  enc_heads: [1, 2, 4]
  middle_heads: 8
  dec_heads: [4, 2, 1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 600000
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: MSL1FFTLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
